#!/bin/sh                                                                                       

PID="net.vertigostudios.myflashlight"
SID="net.vertigostudios.ledmanager"

# Handle execution as pmPostInstall.script
if [ -z "$IPKG_OFFLINE_ROOT" ]; then
  IPKG_OFFLINE_ROOT=/media/cryptofs/apps
  mount -o remount,rw /
fi

APPS=/media/cryptofs/apps

[ -d $APPS ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }

# Install the upstart script
rm -f /etc/event.d/${SID} /var/palm/event.d/${SID}
if [ -d /var/palm/event.d ] ; then
  cp $APPS/usr/palm/applications/${PID}/upstart/${SID} /var/palm/event.d/${SID}
else
  cp $APPS/usr/palm/applications/${PID}/upstart/${SID} /etc/event.d/${SID}
fi

# Install the dbus service
rm -f /usr/share/dbus-1/system-services/${SID}.service /var/palm/system-services/${SID}.service
if [ -d /var/palm/system-services ] ; then
  cp $APPS/usr/palm/applications/${PID}/dbus/${SID}.service /var/palm/system-services/${SID}.service
else
  cp $APPS/usr/palm/applications/${PID}/dbus/${SID}.service /usr/share/dbus-1/system-services/${SID}.service
fi

# Stop any existing service
/sbin/stop ${SID} || true

# Install the ledmanager executable
mkdir -p /var/usr/sbin/
rm -f /var/usr/sbin/${SID}
install -m 755 $APPS/usr/palm/applications/${PID}/bin/${SID} /var/usr/sbin/${SID}

# Start the service
/sbin/start ${SID}

# Check the upstart script is installed
[ -f /var/palm/event.d/${SID} ] || [ -f /etc/event.d/${SID} ] || exit 1

# Check the dbus service is installed
[ -f /var/palm/system-services/${SID}.service ] || [ -f /usr/share/dbus-1/system-services/${SID}.service ] || exit 1

exit 0
