#!/bin/sh

PID="net.vertigostudios.myflashlight"
SID="net.vertigostudios.ledmanager"

# Handle execution as pmPreRemove.script
if [ -z "$IPKG_OFFLINE_ROOT" ]; then
  IPKG_OFFLINE_ROOT=/media/cryptofs/apps
  mount -o remount,rw /
fi

APPS=/media/cryptofs/apps

[ -d $APPS ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }

# Stop the service if running
/sbin/stop ${SID} || true

# Remove the dbus service
rm -f /usr/share/dbus-1/system-services/${SID}.service /var/palm/system-services/${SID}.service

# Remove the upstart script
rm -f /etc/event.d/${SID} /var/palm/event.d/${SID}

# Remove the ledmanager executable
rm -f /var/usr/sbin/${SID}

exit 0
